# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Nightly
version:      0.03
version_from: lib/Test/Nightly.pm
installdirs:  site
requires:
    Carp:                          1.02
    Class::Accessor::Chained:      0.01
    DateTime:                      0.28
    Email::Send:                   1.46
    Email::Simple:                 1.92
    Email::Simple::Creator:        1.4
    File::Find::Rule:              0.26
    File::Spec:                    0.82
    List::Util:                    1.17
    Template:                      1.4
    Test::Harness::Straps:         0.23
    Test::More:                    0.54

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
